<script setup lang="ts">
import { MarkdownDocument } from '@comark/vue'
// import { parseMarkdown } from 'comark'
import toc from 'comark/plugins/toc'
import mermaid, { Mermaid } from '@comark/vue/plugins/mermaid'

const plugins = [toc({ depth: 3, title: 'On This Page' }),mermaid()]

const route = useRoute()
const path = route.path.replace(/\/+$/, '') || '/'
const { data: page, error } = await useAsyncData(path, () => clientContent.get(path))
const island = getIsland('/notes')!

useHead({
  title: island.pageTitle,
  meta: [{ name: 'description', content: island.description }],
})

definePageMeta({
  layout: 'note',
  title: island.pageTitle,
  titleIcon: island.titleIcon,
})

if (error.value) {
  console.error('Content fetch error:', error.value)
}

if (!page.value) {
  throw createError({ statusCode: 404, message: 'Page not found' })
}

const pageTitles = page.value.meta.stem.split('/') || ['Y Đa Khoa']

// Prepend the title as an H1 node directly on the parsed document
/* if (page.value && Array.isArray(page.value.nodes)) {
  const hasH1 = page.value.nodes.some((node) => Array.isArray(node) && node[0] === 'h1')
  if (!hasH1) {
    page.value.nodes.unshift(['h1', {}, pageTitles.pop()])
  }
} */

const noteDir = page.value.meta.key.split('/').slice(0, -1).join('/')

// TOC links generated by the plugin (adjust if your log shows a different path)
const tocLinks = computed(() => page.value?.meta?.toc?.links ?? [])

// console.log(tocLinks.value)
// console.log('Page value', page.value)

const rewriteImgs = (nodes: any[]) => {
  for (const n of nodes) {
    if (!Array.isArray(n)) continue
    if (n[0] === 'img') {
      const props = (n[1] ??= {})
      const raw = (props.src || props.alt || '').trim()
      if (raw && !/^(https?:)?\/\/|^data:|^\//.test(raw)) {
        const key = `${noteDir}/${decodeURIComponent(raw)}`
        props.src = '/media/' + key.split('/').slice(1).map(encodeURIComponent).join('/')
          // props.src = '/api/content/media/' + key.split('/').map(encodeURIComponent).join('/')
        // This come from /api/content/media/, others related code is still there, including addServeHandler and media()
      }
    }
    rewriteImgs(n.slice(2))
  }
}
rewriteImgs(page.value.nodes)
</script>

<template>
  <div
    class="max-w-9/10 lg:max-w-3/5 mt-6 lg:mt-8 prose lg:prose-lg dark:prose-invert prose-headings:font-head mx-auto !max-w-75ch prose-a:no-underline hover:prose-a:text-purple-800/95 dark:hover:prose-a:text-purple-300/90 prose-a:transition-all prose-a:duration-200 prose-headings:tracking-wide prose-table:table-auto prose-table:overflow-scroll prose-table:scrollbar-none prose-table:w-full prose-td:min-w-[calc-size(max-content,min(size,10ch))] prose-img:mx-auto prose-img:rounded-md"
  >
    <NuxtLink class="mb-4 cursor-pointer flex gap-2 opacity-90" to="/notes">
      <div class="i-solar:home-2-bold lg:text-lg" />
      <span class="text-xs lg:text-sm">
        {{ pageTitles[0] }} /
        <span class="opacity-90">
          {{ pageTitles[1] }}
        </span>
      </span>
    </NuxtLink>
    <h1>{{ pageTitles[2] }}</h1>
    <aside v-if="tocLinks.length" class="p-2 border-slate-100 dark:border-slate-800 bg-slate-500/30 [&_li]:list-none [&_li]:pl-0">
	      <h2 class="mb-2 font-semibold opacity-80">Mục lục</h2>
      <TocLinks :links="tocLinks" />
    </aside>
    <MarkdownDocument :value="page" class="" :components="{ mermaid: Mermaid }" :plugins=plugins></MarkdownDocument>
  </div>
</template>

<style>
.prose table {
  width: max-content;
  min-width: 100%;
  max-width: min(calc(100vw - 2rem), 110ch);
  position: relative;
  left: 50%;
  transform: translateX(-50%);
}
</style>
